// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  var lastMessageTime, tmi;

  lastMessageTime = 0;

  tmi = new irc.client({
    options: {
      debug: true
    },
    channels: ['hatsuney']
  });

  tmi.on('connected', (function(_this) {
    return function() {
      return console.log('yay');
    };
  })(this));

  tmi.on('message', (function(_this) {
    return function(channel, user, message, self) {
      setTimeout(function() {
        return $('body').append(' <span class="message animation-slide-up" style="border-left: 5px solid ' + user.color + ';"> <small class="pull-right time">' + moment().format('HH:mm') + '</small> <b class="pull-left" style="padding-left: 3px;">' + user.username + '</b> <br /> ' + message.replace(/(<([^>]+)>)/ig, "") + ' </span>');
      }, lastMessageTime);
      lastMessageTime += 1500;
      console.log(channel);
      console.log(user);
      return console.log(message);
    };
  })(this));

  tmi.connect();

  tmi.emit('message', {}, {
    username: 'whatever'
  }, 'hello', null);

  setInterval((function(_this) {
    return function() {
      lastMessageTime -= 500;
      if (lastMessageTime < 0) {
        return lastMessageTime = 0;
      }
    };
  })(this), 500);

}).call(this);
